//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SquareGrid.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Layouts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Layouts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SquareGrid.Common.Resources.Layouts", typeof(Layouts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;title&gt;{{title}}&lt;/title&gt;
        ///        &lt;meta name=&quot;description&quot; content=&quot;{{description}}&quot; /&gt;
        ///        &lt;link rel=&quot;canonical&quot; href=&quot;{{url}}&quot; /&gt;
        ///        &lt;meta name=&quot;robots&quot; content=&quot;index, follow&quot; /&gt;
        ///        &lt;meta property=&quot;og:title&quot; content=&quot;{{title}}&quot; /&gt;
        ///        &lt;meta property=&quot;og:description&quot; content=&quot;{{description}}&quot; /&gt;
        ///        &lt;meta property=&quot;og:url&quot; content=&quot;{{url}}&quot; /&gt;
        ///        &lt;meta property=&quot;og:type&quot; content=&quot;website&quot; /&gt;
        ///        &lt;meta property=&quot;og:image&quot; content=&quot;{{image}}&quot; /&gt;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Redirect {
            get {
                return ResourceManager.GetString("Redirect", resourceCulture);
            }
        }
    }
}
