@baseUrl = http://localhost:7059/api

GET https://ourgameauth.b2clogin.com/ourgameauth.onmicrosoft.com/b2c_1_susi/oauth2/v2.0/authorize
?client_id=017c1045-b0db-4e87-bc13-87d68dce0185
&response_type=code
&redirect_uri=http://localhost:3000/api/auth/callback/azure-ad-b2c
&scope=offline_access openid https://ourgameauth.onmicrosoft.com/sg-api/app.read https://ourgameauth.onmicrosoft.com/sg-api/app.write
Content-Type: application/x-www-form-urlencoded

###

# @name tokenRequest
POST https://ourgameauth.b2clogin.com/ourgameauth.onmicrosoft.com/b2c_1_susi/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code&client_secret=01e8Q~ZIUobfVCMiWIKaIq1UzQQhTZhX0ESr8aqu
&client_id=017c1045-b0db-4e87-bc13-87d68dce0185
&redirect_uri=http://localhost:3000/api/auth/callback/azure-ad-b2c
&scope=offline_access openid https://ourgameauth.onmicrosoft.com/sg-api/app.read https://ourgameauth.onmicrosoft.com/sg-api/app.write
&code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjEuMCIsInppcCI6IkRlZmxhdGUiLCJzZXIiOiIxLjAifQ..VgQzjCYylOc5bloB.ropNxgwOseSgrUDTV0NvjWEuirdyOl6rgEA1s9yOqkx-QkWO1opY95yBlUZFgnIRazDlKQFfvCcGvWP7fYjy2m8ENmHIhRmtsYAZAYe_Q4PqTTltSKTRh64jnfWqr-3jzMi-rhxd8pbIWFFqU0lnXXywgaW8HSg-MiMhVwo44MznIlFlx1ymcnT8VCzluuJNV-OQ5ytXl3ypZ6CgqFo--h9tfg5mwy8ut7eFVlcKsDQUxI7-IJAPsGtAX9VuGgWy7V4kGHELVJ5GORgEjVobr3nguUgnVQp-7k5cjap5UTPW-odPnIOkpoZXkcRyWz50cC3pub9uHBZiIuz-B4L7dpBS2s_fBsl5GIp5T0b0Nrqc6jZNIzRfx5Cdz4_DlPDX0ZiS6sroG95Df6yZY-WRsLtB-IajYWoE9EoM_uftl4n2vH23PsLvwg4X8jPl9b1PfhCFIUmLSG04LN5DZ-Mol5bOs6JtRLzf9ip9c4Yk0Jo42fDAKxgM3oMBcdbTM55MCW7-vgC3Z0KGtumg20zMb9dNqjJHuZXHkfOxjRNBXdThH9nGoq_ajup-QQJhmVbXDs_g-5lAzpJ9keSLgacRQlaCo60buQ.XhmUgKvhfqyg4626vTpWxQ

###

@authToken = {{tokenRequest.response.body.id_token}}

# @name get
GET {{baseUrl}}/games/f3b07384-d113-4ec8-98c1-eb1a5c48f0b1 HTTP/1.1
Accept: application/json
Authorization: {{authToken}}

###

# @name list
GET {{baseUrl}}/games HTTP/1.1
Accept: application/json
Authorization: {{authToken}}

###

# @name add
PUT {{baseUrl}}/games HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
  "partitionKey": "242e3343-4348-4068-83b1-57bbdc5a4e02",
  "rowKey": "f3b07384-d113-4ec8-98c1-eb1a5c48f0b1",
  "title": "Epic Space Adventure",
  "image": "https://example.com/images/space-adventure.png",
  "description": "An epic game of exploration and battles in the vastness of space.",
  "published": false,
  "blocks": 50,
  "blocksClaimed": 0,
  "blocksRemaining": 50,
  "isCompleted": false,
  "isWon": false,
  "timestamp": "2024-04-01T22:13:35.4574199+00:00",
  "eTag": "W/\"datetime'2024-04-01T22%3A13%3A35.4574199Z'\""
}

###

# @name update
POST {{baseUrl}}/games HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
  "partitionKey": "242e3343-4348-4068-83b1-57bbdc5a4e02",
  "rowKey": "f3b07384-d113-4ec8-98c1-eb1a5c48f0b1",
  "title": "Epic New Space Adventure",
  "image": "https://example.com/images/space-adventure.png",
  "description": "An epic game of exploration and battles in the vastness of space.",
  "published": false,
  "blocks": 50,
  "blocksClaimed": 0,
  "blocksRemaining": 50,
  "isCompleted": false,
  "isWon": false,
  "timestamp": "2024-05-27T16:20:52.4563248+00:00",
  "eTag": "W/\"datetime'2024-05-27T16%3A20%3A52.4563248Z'\""
}

###

# @name userImage
POST {{baseUrl}}/images/user HTTP/1.1
Authorization: {{authToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryE19zNvXGzXaLvS5C

------WebKitFormBoundaryE19zNvXGzXaLvS5C
Content-Disposition: form-data; name="file"; filename="transparent.png"
Content-Type: image/png

<89 50 4E 47 0D 0A 1A 0A 00 00 00 0D 49 48 44 52 00 00 00 01 00 00 00 01 08 06 00 00 00 1F 15 C4 89 00 00 00 0C 49 44 41 54 78 9C 63 60 00 00 00 02 00 01 E2 21 BC 33 00 00 00 00 49 45 4E 44 AE 42 60 82>
------WebKitFormBoundaryE19zNvXGzXaLvS5C--

###

# @name gameImage
POST {{baseUrl}}/images/game/f3b07384-d113-4ec8-98c1-eb1a5c48f0b1 HTTP/1.1
Authorization: {{authToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryE19zNvXGzXaLvS5C

------WebKitFormBoundaryE19zNvXGzXaLvS5C
Content-Disposition: form-data; name="file"; filename="transparent.png"
Content-Type: image/png

<89 50 4E 47 0D 0A 1A 0A 00 00 00 0D 49 48 44 52 00 00 00 01 00 00 00 01 08 06 00 00 00 1F 15 C4 89 00 00 00 0C 49 44 41 54 78 9C 63 60 00 00 00 02 00 01 E2 21 BC 33 00 00 00 00 49 45 4E 44 AE 42 60 82>
------WebKitFormBoundaryE19zNvXGzXaLvS5C--